[package]
authors = ["David Sullins <david.sullins@gmail.com>"]
description = "Advent of Code 2016 solutions in Rust"
license = "MIT"
name = "AdventOfRust2016"
version = "0.1.0"

[dependencies]
lazy_static = "0.2"
md5 = "0.3"
regex = "0.1"
